easy_admin:
  entities:
    User:
      class: App\Entity\User
      label: 'User'
      list:
        fields: ['id','email','name','roles','statusUser','companyLimit']
      edit:
        fields:
          - email
          - name
          - statusUser
          - companies
          - companyLimit
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices:{ 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN'}} }
      new:
        fields: ['email','password','name']
    Bill:
      class: App\Entity\Bill
      label: 'Bill'
    Client:
      class: App\Entity\Client
      label: 'Client'
    Company:
      class: App\Entity\Company
      label: 'Company'
    Product:
      class: App\Entity\Product
      label: 'Product'
    SocialNetworks:
      class: App\Entity\SocialNetworks
      label: 'SocialNetworks'
    BillLine:
      class: App\Entity\BillLine
      label: 'BillLine'
    Budget:
      class: App\Entity\Budget
      label: 'Budget'
